### ISSUE TITLE
No newline after each stream written by `ion dump -f pretty`

### ISSUE THREAD

**Issue by zslayton** [amazon-ion/ion-cli#36]
Related to amzn/ion-rust#437.

When dumping multiple input files, the missing trailing newline causes the last and first values in successive streams to run together, modifying the data or producing illegal syntax.

![image](https://user-images.githubusercontent.com/611616/199821407-8f1d11e5-5d7d-4508-a004-a8f482259601.png)

Note that the `3` at the end of each stream and the `1` of the next stream are concatenated to form legal-but-wrong `31`s.

**Comment by jobarr-amzn** [comment]
This also applies for the `lines` format, and more generally.
