### ISSUE TITLE
Dump to JSON

### ISSUE THREAD

**Issue by SimplyKnownAsG** [amazon-ion/ion-cli#40]
I commonly want to transform ION to JSON because it can be more readable, and works well with `jq`.

**Comment by popematt** [comment]
Thanks for the feature request! While we intend to eventually add support for downconversion to JSON, it's not something we're actively working on right now. Are you interested in contributing to this feature?

We're always interested to learn more about the pain points that people have when using Ion. When you say that JSON is more readable, do you mean from a human perspective or from a system interoperability perspective? Would you be willing to share more details about your use case where JSON is more efficient (and what you are using as your measure of efficiency)?

**Comment by SimplyKnownAsG** [comment]
Good clarification. It is more readable from system interoperability perspective.

The use case for JSON being more efficient is solely based on DynamoDB storage, not the size on (my) disk. I'll remove that from the description because it is misleading.

**Comment by popematt** [comment]
> It is more readable from system interoperability perspective.

Yes. JSON is ubiquitous, and we do recognize the need to convert to JSON to integrate with other systems.

> The use case for JSON being more efficient is solely based on DynamoDB storage

No need to remove it—this is interesting. The difference in storage size is going to be affected by the data that you are storing and the way you choose to model it in DynamoDB. If your data is more than a single primitive or an empty collection, then we would expect that an Ion binary blob stored in a DynamoDB `B` value would be smaller than storing a JSON string as a DynamoDB `S` value. However, if you are converting from JSON to DynamoDB JSON, then there may be some optimizations in the DynamoDB storage layer that make it smaller to use DynamoDB JSON.

I'm also curious—would it be valuable for you to be able to go straight from Ion to DynamoDB JSON without needing to use "regular" JSON as an intermediate step? (For example, JSON can lose precision on numbers, whereas DynamoDB JSON encodes numbers as strings to avoid any potential precision loss, so you may have better fidelity if you are converting from an Ion decimal directly to a DynamoDB number.)

**Comment by SimplyKnownAsG** [comment]
Normal JSON is best. DynamoDB JSON would be cool too.

**Comment by jobarr-amzn** [comment]
As far as I understand it this is resolved by #44  (I remembered this issue when reviewing #54 ).
