### ISSUE TITLE
Make `to json` for clob and blob more robust

### ISSUE THREAD

**Issue by tgregg** [amazon-ion/ion-cli#45]
Currently, down-converting Ion blobs and clobs to JSON strings involves getting the text Ion representation of the values and chopping off the `{{`, `{{"`, etc. This is fragile because it relies on a canonical text representation, which isn't guaranteed. A more robust technique would be to reuse the code from ion-rust that creates the text representation of the blob/clob context without the surrounding syntax.

See #44

**Comment by zslayton** [comment]
This was fixed by #52. `blob` and `clob` are now transcribed to JSON by directly encoding their `&[u8]` data using the `base64` crate.
