### ISSUE TITLE
Iteratively parse top-level values in `inspect` and `to`

### ISSUE THREAD

**Issue by tgregg** [amazon-ion/ion-cli#47]
https://github.com/amazon-ion/ion-rust/pull/485 introduces the ability to iteratively parse top-level values from a stream. Previously, only `@[u8]` was supported as input, forcing `inspect` and `to` to memory-map the stream (e.g., https://github.com/amazon-ion/ion-cli/blob/master/src/bin/ion/commands/beta/inspect.rs#L182).

The duplicate logic in `inspect` and `to` should be updated to use the improved API.

**Comment by zslayton** [comment]
This was addressed in #113.
