### ISSUE TITLE
Promote beta subcommands to stable

### ISSUE THREAD

**Issue by desaikd** [amazon-ion/ion-cli#63]
Currently we have all the following subcommands in `beta-subcommands` feature. In order to make it available with default installation of `ion-cli` move away stable subcommands from `beta-subcommands` feature and from `beta` namespace.

- [ ] from/to 
- [ ] schema load
- [ ] schema validate
- [ ] symtab filter
- [ ] head
- [ ] count
- [ ] inspect
- [ ] primitive

**Comment by popematt** [comment]
I'm going to mark this as complete since we added the `-X` flag in #128 .
